//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEXApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class GearList
    {
        public int Id { get; set; }
        
        [Display(Name="Gear")]
        [StringLength(50,MinimumLength=1)]
        public string Gear { get; set; }

        [Display(Name = "Model Description")]
        [StringLength(50, MinimumLength = 1)]
        public string Model { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Check-Out Date")]
        public Nullable<System.DateTime> DateOut { get; set; }
        
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Check-In Date")]

        public Nullable<System.DateTime> DateIn { get; set; }

        [StringLength(50, ErrorMessage = "Check out by field cannot be longer than 50 characters.")]
        [Display(Name = "Check-Out By")]
        public string CheckOutBy { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Bought On")]
        public System.DateTime CreatedDate { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Last Updated On")]
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool isActive { get; set; }
    }
}
